### ISSUE TITLE
AttributeError: 'float' object has no attribute 'strip'

### ISSUE THREAD

**Issue by GuanglinHe1** [Shuhua-Group/Y-LineageTracker#1]
Dear Hao Chen and Prof. Xu,
I can run the cluster model with the example data, however, when we run the cluster model with the new-sequenced data, the following errors occurred. Would you mind sharing some ideas for this error.?

**Script**: LineageTracker cluster --hg KGP_hgs1.hg -p KGP_pops1.pop

[**Errors**:](url)
[Y-LineageTracker] [Cluster]
[Y-LineageTracker] Run Date: Tue Jan 11 19:11:48 2022
[Y-LineageTracker] Input File: KGP_hgs1.hg
[Y-LineageTracker] Clustering Method: pca
[Y-LineageTracker] Haplogroup Level: original
Traceback (most recent call last):
  File "/home/.local/bin/LineageTracker", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.9/site-packages/LineageTracker/RunLineagerTracker.py", line 45, in main
    ClusterHaplogroup.main()
  File "/home/.local/lib/python3.9/site-packages/LineageTracker/ClusterHaplogroup.py", line 494, in main
    hap_data = check_hap_input(arguments.hg, 'haplogroup')
  File "/home/.local/lib/python3.9/site-packages/LineageTracker/FilesIO.py", line 317, in check_hap_input
    input_data['Haplogroup'] = input_data['Haplogroup'].map(lambda x: x.strip('~'))
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/pandas/core/series.py", line 4161, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/home/administrator/miniconda3/lib/python3.9/site-packages/pandas/core/base.py", line 870, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "/home/.local/lib/python3.9/site-packages/LineageTracker/FilesIO.py", line 317, in <lambda>
    input_data['Haplogroup'] = input_data['Haplogroup'].map(lambda x: x.strip('~'))
AttributeError: 'float' object has no attribute 'strip'
But some subset data can be run succesffully.
[Cluster.PCA.fig.pdf](https://github.com/Shuhua-Group/Y-LineageTracker/files/7846022/Cluster.PCA.fig.pdf)

**Comment by HaoChen-PGG** [comment]
Hi Guanglin,
    It seems that there are NA in the 'Haplogroup' column. These NAs are regarded as float in Python. Please check your input haplogroup file and ensure there is no missing values.
