### ISSUE TITLE
AttributeError: module 'matplotlib.font_manager' has no attribute 'createFontList'

### ISSUE THREAD

**Issue by Lomousmishra** [Shuhua-Group/Y-LineageTracker#2]
Hi,
My system have Python3.8 and matplotlib3.5.1 installed.
While trying network using your test data got following error:
Traceback (most recent call last):
  File "/usr/local/bin/LineageTracker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/LineageTracker/RunLineagerTracker.py", line 54, in main
    HaploNetwork.main()
  File "/usr/local/lib/python3.8/dist-packages/LineageTracker/HaploNetwork.py", line 1006, in main
    net.calculate_and_output(haplotype_data, population_data, arguments, label)
  File "/usr/local/lib/python3.8/dist-packages/LineageTracker/HaploNetwork.py", line 950, in calculate_and_output
    length_data, DG, pos, hap_size, hap_freq, hap_size_per, hap_freq_per, style_list, pops, trans, trans2, fig_len = self._get_figure_parameters(sequence_df, population_data, plot_network_data, alt_data, node_num, network_data.size, arguments.alt, arguments.euqalsize, label)
  File "/usr/local/lib/python3.8/dist-packages/LineageTracker/HaploNetwork.py", line 834, in _get_figure_parameters
    font_list = font_manager.createFontList(font_files)
AttributeError: module 'matplotlib.font_manager' has no attribute 'createFontList'

Please suggest a solution for this error.
Lomous

**Comment by HaoChen-PGG** [comment]
Hi Lomous,
    I'm sorry for this error. This could be caused by the version mismatch of Python and Matplotlib. 
    The matplotlib.font_manager.createFontList is removed in the matplotlib3.5.1. Maybe you can try a matplotlib3.1.1 under the Python 3.6.
    I'll update the program with the newer Python and Python packages.
