### ISSUE TITLE
failes to test y lineage 

### ISSUE THREAD

**Issue by Shaileshdesai76** [Shuhua-Group/Y-LineageTracker#5]
i have installed all the dependencies and testing y lineage tracker, though it giving me error 

ineageTracker test
[Y-LineageTracker] Testing classify command...
[Y-LineageTracker] Failed in testing classify command
[Y-LineageTracker] Testing cluster command...
[Y-LineageTracker] Failed in testing cluster command
[Y-LineageTracker] Testing phylo command...
[Y-LineageTracker] Successfully tested phylo command
[Y-LineageTracker] Testing genostr command...
[Y-LineageTracker] Successfully tested genostr command
[Y-LineageTracker] Testing net command...
[Y-LineageTracker] Failed in testing net command
[Y-LineageTracker] Testing stat command...
[Y-LineageTracker] Predicting haplogroups from Y-STR data…… 100.00%
[Y-LineageTracker] Successfully tested stat command
[Y-LineageTracker] Testing time command...
[Y-LineageTracker] Failed in testing time command
[Y-LineageTracker] Testing tmrca command...
[Y-LineageTracker] Successfully tested tmrca command
(base) gyanlab@gl:~/Desktop/Anjana/Y Chrom/Raw_file$ LineageTracker classify -b 37 --vcf Anjana\ \(SriLanka\)_Y_raw_Y.2.vcf.gz

[Y-LineageTracker] [Y-Haplogroup Classification]
[Y-LineageTracker] Run Date: Fri Oct 20 12:10:37 2023
[Y-LineageTracker] Input File: Anjana (SriLanka)_Y_raw_Y.2.vcf.gz
[Y-LineageTracker] File Format: gzvcf
[Y-LineageTracker] Reference Build: 37
[Y-LineageTracker] Data Type: WGS
[Y-LineageTracker] Reading input file...
Killed
(base) gyanlab@gl:~/Desktop/Anjana/Y Chrom/Raw_file$

**Comment by Shaileshdesai76** [comment]
then again i did re-run, now giving this output. 
no module "Numpy" found, but you can see it is there 
(base) gyanlab@gl:~$ pip install Y-LineageTracker
Requirement already satisfied: Y-LineageTracker in ./miniconda3/lib/python3.8/site-packages (1.3.0)
Requirement already satisfied: pandas in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (2.0.3)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (1.24.4)
Requirement already satisfied: scikit-learn in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (1.3.0)
Requirement already satisfied: scipy in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (1.10.1)
Requirement already satisfied: matplotlib in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (3.7.3)
Requirement already satisfied: ete3 in ./miniconda3/lib/python3.8/site-packages/ete3-3.1.3-py3.10.egg (from Y-LineageTracker) (3.1.3)
Requirement already satisfied: networkx in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (3.1)
Requirement already satisfied: BioPython in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (1.81)
Requirement already satisfied: pysam in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (0.9.1)
Requirement already satisfied: pyqt5 in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (5.15.10)
Requirement already satisfied: adjustText in ./miniconda3/lib/python3.8/site-packages (from Y-LineageTracker) (0.8)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (1.0.5)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (23.0)
Requirement already satisfied: pillow>=6.2.0 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (10.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in ./miniconda3/lib/python3.8/site-packages (from matplotlib->Y-LineageTracker) (6.0.0)
Requirement already satisfied: pytz>=2020.1 in ./miniconda3/lib/python3.8/site-packages (from pandas->Y-LineageTracker) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./miniconda3/lib/python3.8/site-packages (from pandas->Y-LineageTracker) (2023.3)
Requirement already satisfied: PyQt5-sip<13,>=12.13 in ./miniconda3/lib/python3.8/site-packages (from pyqt5->Y-LineageTracker) (12.13.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in ./miniconda3/lib/python3.8/site-packages (from pyqt5->Y-LineageTracker) (5.15.2)
Requirement already satisfied: joblib>=1.1.1 in ./miniconda3/lib/python3.8/site-packages (from scikit-learn->Y-LineageTracker) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./miniconda3/lib/python3.8/site-packages (from scikit-learn->Y-LineageTracker) (2.2.0)
Requirement already satisfied: zipp>=3.1.0 in ./miniconda3/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->Y-LineageTracker) (3.16.2)
Requirement already satisfied: six>=1.5 in ./miniconda3/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->Y-LineageTracker) (1.16.0)
(base) gyanlab@gl:~$ LineageTracker test
Traceback (most recent call last):
  File "/home/gyanlab/miniconda3/bin/LineageTracker", line 33, in <module>
    sys.exit(load_entry_point('Y-LineageTracker==1.3.0', 'console_scripts', 'LineageTracker')())
  File "/home/gyanlab/miniconda3/lib/python3.8/site-packages/LineageTracker/RunLineagerTracker.py", line 37, in main
    from Test import TestProgram
  File "/home/gyanlab/miniconda3/lib/python3.8/site-packages/LineageTracker/Test/TestProgram.py", line 6, in <module>
    import pandas as pd
  File "/home/gyanlab/miniconda3/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'
